### ISSUE TITLE
$USER Error 

### ISSUE THREAD

**Issue by MomciloCulic** [trkin/dev.trk.in.rs#1]
There is an error in this line of code: 
```
echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /home/$USER/.profile
echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/$USER/.profile
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

```
Solution of this is to use your username instead of $USER.

**Comment by duleorlovic** [comment]
I can not reproduce this so I think it is fine to keep `$USER` https://github.com/trkin/dev.trk.in.rs/blob/master/_posts/2023-01-11-bash-related-commands.md#brew
